name: CI for production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Firebase tools
      run: sudo npm install -g firebase-tools
    - name: Build Website
        run: |
          npm ci
          npm run build
    - name: Deploy to Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: sudo firebase deploy -P default --token "$FIREBASE_TOKEN"
